spring:
  jpa:
    show-sql: true
    properties:
      format_sql: true
      dialect: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: validate

  datasource:
    url: jdbc:mariadb://localhost:3306/simple_board?useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: root